# Generated by Django 3.0.7 on 2022-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('sent', 'Enviado'), ('delivered', 'Entregado')], default='new', max_length=50, verbose_name='Estatus'),
        ),
    ]
