# Generated by Django 3.0.7 on 2022-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220329_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('confirmed', 'Confirmado'), ('paid', 'Pagado'), ('delivered', 'Entregado')], default='new', max_length=50, verbose_name='Estatus'),
        ),
    ]
