# Generated by Django 3.0.7 on 2022-03-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_auto_20220329_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_payment', models.CharField(choices=[('cash', 'Efectivo'), ('check', 'Cheque'), ('debit_card', 'Tarjeta Débito'), ('credit_card', 'Tarjeta de Crédito'), ('transfer', 'Transferencia')], default='cash', max_length=50, null=True, verbose_name='Método de Pago')),
                ('value', models.FloatField(null=True, verbose_name='Valor')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment', verbose_name='Payment')),
            ],
        ),
    ]
